### PR TITLE
Implement model admin with option to enable/disable

### PR DESCRIPTION
**Pull request by satrun77**
- Make use of site config extension of model admin to manage the site banner optional using environment variables. 
- Add Alert type to banners grid field.

### CODE REVIEW

**Review by Jianbinzhu — APPROVED** [review]
Nice! Loving those feature flags 😍

**Comment by madmatt** [comment]
Hey team, this is pretty old at this point, but just wondering what prompted this change? Now we have two different interfaces that need to be tested separately, implement features separately etc. It's only the CMS interface and the module doesn't do a _lot_ of things, but I'm just wondering where the suggestion for this came from.

Thank you! 🙏🏼

**Comment by satrun77** [comment]
Short answer security.

Long answer. The old way of managing banners from settings is deprecated and won't receive features or support! It's still there just for backward compatibility if someone still like old way! And it's why uses environment variable to enable disable!

The change because most of the time this module is added to a project we are adding custom code to disable the site settings interface for model admin interface! There are cms users with only access to manage banners, when the interface is part of the settings this means users have to be given full access just to do one thing managing banners. 

Also using model admin removed that dependency between unrelated data.

**Comment by madmatt** [comment]
Hey @satrun77, thanks for that, makes sense to me. We should add a comment to mention that the `SiteConfig` interface isn't getting further updates and that we recommend using the separate `ModelAdmin` interface for security reasons.

**Pull request merged**
